<?php
$email_templates = array(
    'admin_password_reset'=>array(
        'id'=>'admin_password_reset',
        'type'=>'user',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'admin_password_reset_request'=>array(
        'id'=>'admin_password_reset_request',
        'type'=>'user',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'contact_response'=>array(
        'id'=>'contact_response',
        'type'=>'general',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'order_status_change'=>array(
        'id'=>'order_status_change',
        'type'=>'order',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'admin_listings_send_email_friend'=>array(
        'id'=>'admin_listings_send_email_friend',
        'type'=>'listing',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'admin_listings_send_email'=>array(
        'id'=>'admin_listings_send_email',
        'type'=>'listing',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'admin_listings_claim'=>array(
        'id'=>'admin_listings_claim',
        'type'=>'listing',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'listings_claim'=>array(
        'id'=>'listings_claim',
        'type'=>'listing',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'user_listing_update'=>array(
        'id'=>'user_listing_update',
        'type'=>'user',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'listings_suggestion'=>array(
        'id'=>'listings_suggestion',
        'type'=>'listing',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'admin_listings_suggestion'=>array(
        'id'=>'admin_listings_suggestion',
        'type'=>'listing',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'password_reset_request'=>array(
        'id'=>'password_reset_request',
        'type'=>'user',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'password_reset'=>array(
        'id'=>'password_reset',
        'type'=>'user',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'admin_bot_detection'=>array(
        'id'=>'admin_bot_detection',
        'type'=>'general',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'user_registration'=>array(
        'id'=>'user_registration',
        'type'=>'user',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'admin_user_registration'=>array(
        'id'=>'admin_user_registration',
        'type'=>'user',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'invoice_overdue_1'=>array(
        'id'=>'invoice_overdue_1',
        'type'=>'invoice',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'invoice_reminder'=>array(
        'id'=>'invoice_reminder',
        'type'=>'invoice',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'invoice_created'=>array(
        'id'=>'invoice_created',
        'type'=>'invoice',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'invoice_overdue_2'=>array(
        'id'=>'invoice_overdue_2',
        'type'=>'invoice',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'invoice_overdue_3'=>array(
        'id'=>'invoice_overdue_3',
        'type'=>'invoice',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'admin_cron_summary'=>array(
        'id'=>'admin_cron_summary',
        'type'=>'general',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'admin_listing_review_submitted'=>array(
        'id'=>'admin_listing_review_submitted',
        'type'=>'review',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'listing_review_submitted'=>array(
        'id'=>'listing_review_submitted',
        'type'=>'review',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'updates_rejected'=>array(
        'id'=>'updates_rejected',
        'type'=>'general',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'updates_approved'=>array(
        'id'=>'updates_approved',
        'type'=>'general',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'order_submitted'=>array(
        'id'=>'order_submitted',
        'type'=>'order',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'admin_order_submitted'=>array(
        'id'=>'admin_order_submitted',
        'type'=>'order',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'admin_update_submitted'=>array(
        'id'=>'admin_update_submitted',
        'type'=>'general',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'admin_invoice_payment'=>array(
        'id'=>'admin_invoice_payment',
        'type'=>'invoice',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'invoice_payment'=>array(
        'id'=>'invoice_payment',
        'type'=>'invoice',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'listing_claim_approved'=>array(
        'id'=>'listing_claim_approved',
        'type'=>'listing',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'listing_claim_denied'=>array(
        'id'=>'listing_claim_denied',
        'type'=>'listing',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'listing_review_submitted_notification'=>array(
        'id'=>'listing_review_submitted_notification',
        'type'=>'review',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'admin_order_upgrade'=>array(
        'id'=>'admin_order_upgrade',
        'type'=>'order',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'admin_cancellation_request'=>array(
        'id'=>'admin_cancellation_request',
        'type'=>'order',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'cancellation_request_response'=>array(
        'id'=>'cancellation_request_response',
        'type'=>'order',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'user_email_confirmation_reminder'=>array(
        'id'=>'user_email_confirmation_reminder',
        'type'=>'user',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'listings_statistics'=>array(
        'id'=>'listings_statistics',
        'type'=>'listing',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'admin_user_update'=>array(
        'id'=>'admin_user_update',
        'type'=>'user',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'listings_send_email_copy'=>array(
        'id'=>'listings_send_email_copy',
        'type'=>'listing',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'admin_order_changed'=>array(
        'id'=>'admin_order_changed',
        'type'=>'order',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'admin_import_status'=>array(
        'id'=>'admin_import_status',
        'type'=>'general',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'admin_contact_submission'=>array(
        'id'=>'admin_contact_submission',
        'type'=>'general',
        'from_name'=>'*name*',
        'reply_name'=>'*name*',
        'reply_address'=>'*email*'
    ),
    'listings_send_email_friend'=>array(
        'id'=>'listings_send_email_friend',
        'type'=>'listing',
        'from_name'=>'*from_name*',
        'reply_name'=>'*from_name*',
        'reply_address'=>'*from_email*'
    ),
    'listings_send_email'=>array(
        'id'=>'listings_send_email',
        'type'=>'listing',
        'from_name'=>'*from_name*',
        'reply_name'=>'*from_name*',
        'reply_address'=>'*from_email*'
    ),
    'admin_reciprocal_failed'=>array(
        'id'=>'admin_reciprocal_failed',
        'type'=>'listing',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'admin_website_failed'=>array(
        'id'=>'admin_website_failed',
        'type'=>'listing',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'reciprocal_failed'=>array(
        'id'=>'reciprocal_failed',
        'type'=>'listing',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'contact_request'=>array(
        'id'=>'contact_request',
        'type'=>'listing',
        'from_name'=>NULL,
        'reply_name'=>'*contact_name*',
        'reply_address'=>'*contact_email*',
    ),
    'contact_request_approved'=>array(
        'id'=>'contact_request_approved',
        'type'=>'user',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL,
    ),
    'admin_contact_request_submitted'=>array(
        'id'=>'admin_contact_request_submitted',
        'type'=>'user',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL,
    ),
    'message_new'=>array(
        'id'=>'message_new',
        'type'=>'user',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL,
    ),
    'message_new_reply'=>array(
        'id'=>'message_new_reply',
        'type'=>'user',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL,
    ),
    'blog_comment_submitted'=>array(
        'id'=>'blog_comment_submitted',
        'type'=>'blog',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL,
    ),
    'admin_blog_comment_submitted'=>array(
        'id'=>'admin_blog_comment_submitted',
        'type'=>'blog',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL,
    ),
    'admin_blog_user_submitted'=>array(
        'id'=>'admin_blog_user_submitted',
        'type'=>'blog',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL,
    ),
    'admin_blog_user_deleted'=>array(
        'id'=>'admin_blog_user_deleted',
        'type'=>'blog',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL,
    ),
    'admin_blog_user_edited'=>array(
        'id'=>'admin_blog_user_edited',
        'type'=>'blog',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL,
    ),
    'blog_post_followers_update'=>array(
        'id'=>'blog_post_followers_update',
        'type'=>'blog',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL,
    ),
    'events_rsvp_new'=>array(
        'id'=>'events_rsvp_new',
        'type'=>'event',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL,
    ),
    'events_expired_new'=>array(
        'id'=>'events_expired_new',
        'type'=>'event',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL,
    ),
    'admin_events_expired_new'=>array(
        'id'=>'admin_events_expired_new',
        'type'=>'event',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL,
    ),
    'admin_events_new'=>array(
        'id'=>'admin_events_new',
        'type'=>'event',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL,
    ),
    'admin_events_edit'=>array(
        'id'=>'admin_events_edit',
        'type'=>'event',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL,
    ),
    'events_rsvp_reminder'=>array(
        'id'=>'events_rsvp_reminder',
        'type'=>'event',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL,
    ),
    'events_approved'=>array(
        'id'=>'events_approved',
        'type'=>'event',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL,
    ),
    'jobs_approved'=>array(
        'id'=>'jobs_approved',
        'type'=>'job',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL,
    ),
    'admin_jobs_new'=>array(
        'id'=>'admin_jobs_new',
        'type'=>'job',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL,
    ),
    'admin_jobs_edit'=>array(
        'id'=>'admin_jobs_edit',
        'type'=>'job',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL,
    ),
    'classifieds_email'=>array(
        'id'=>'classifieds_email',
        'type'=>'classified',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'classifieds_email_copy'=>array(
        'id'=>'classifieds_email_copy',
        'type'=>'classified',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
    'admin_classifieds_email'=>array(
        'id'=>'admin_classifieds_email',
        'type'=>'classified',
        'from_name'=>NULL,
        'reply_name'=>NULL,
        'reply_address'=>NULL
    ),
);
return $email_templates;
?>